In [15]:
import pandas as pd
import plotly.express as px

TARGET_PATH = './data/data.csv'

df = pd.read_csv(TARGET_PATH, encoding='utf-8')

df.head()

,출발항코드(DEPARTURE_PORT_CODE),출발항명(DEPARTURE_PORT_NAME),도착항코드(DEST_PORT_CODE),도착항명(DEST_PORT_NAME),도착항국가(DEST_COUNTRY),기준일자(DATE),항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE)
0,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-05-28,23.69,644.50,0.0,7.94
1,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,22.01,608.54,0.0,16.20
2,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,16.52,749.45,0.0,1.36
3,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,22.37,634.28,0.0,7.44
4,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,16.37,654.99,0.0,1.80

In [16]:
df.shape

(480, 10)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   출발항코드(DEPARTURE_PORT_CODE)  480 non-null    str
 1   출발항명(DEPARTURE_PORT_NAME)   480 non-null    str
 2   도착항코드(DEST_PORT_CODE)       480 non-null    str
 3   도착항명(DEST_PORT_NAME)        480 non-null    str
 4   도착항국가(DEST_COUNTRY)         426 non-null    str
 5   기준일자(DATE)                  480 non-null    str
 6   항만효율성(PORT_EFFICIENCY)      480 non-null    float64
 7   총항해시간(TOTAL_SAILING_TIME)   480 non-null    float64
 8   대기시간(WAITING_TIME)          480 non-null    float64
 9   항만정시성(ON_TIME_PERFORMANCE)  480 non-null    float64
dtypes: float64(4), str(6)
memory usage: 59.8 KB

In [18]:
df.isnull().sum()

출발항코드(DEPARTURE_PORT_CODE)     0
출발항명(DEPARTURE_PORT_NAME)      0
도착항코드(DEST_PORT_CODE)          0
도착항명(DEST_PORT_NAME)           0
도착항국가(DEST_COUNTRY)           54
기준일자(DATE)                     0
항만효율성(PORT_EFFICIENCY)         0
총항해시간(TOTAL_SAILING_TIME)      0
대기시간(WAITING_TIME)             0
항만정시성(ON_TIME_PERFORMANCE)     0
dtype: int64

In [19]:
df.describe()

,항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE)
count,480.000000,480.000000,480.000000,480.000000
mean,19.756458,432.292521,0.138042,6.431250
std,5.754084,415.966180,0.269674,25.602098
min,6.950000,28.970000,0.000000,-322.050000
25%,16.350000,75.985000,0.000000,1.940000
50%,18.735000,327.210000,0.030000,7.645000
75%,21.427500,624.942500,0.170000,13.950000
max,47.010000,1632.540000,3.040000,135.920000

In [20]:
df_copy = df.copy()

df_copy = df_copy.rename(columns={
    '기준일자(DATE)': '기준일자', '항만효율성(PORT_EFFICIENCY)': '항만효율성', '총항해시간(TOTAL_SAILING_TIME)': '총항해시간', '대기시간(WAITING_TIME)': '대기시간', '항만정시성(ON_TIME_PERFORMANCE)': '항만정시성'})

df_copy['기준일자'] = pd.to_datetime(df_copy['기준일자'])

In [21]:
total_df = (
    df_copy[df_copy['도착항코드(DEST_PORT_CODE)'] == 'KPLI'][['기준일자', '항만효율성', '총항해시간', '대기시간', '항만정시성']]
    .rename(columns={'항만효율성': '종합항만효율성', '총항해시간': '종합총항해시간', '대기시간': '종합대기시간', '항만정시성': '종합항만정시성'}).copy()
)

route = df_copy[df_copy['도착항코드(DEST_PORT_CODE)'] != 'KPLI'].copy()

In [22]:
daily_avg = (
    route.groupby('기준일자')
    .agg(평균_항만효율성=('항만효율성', 'mean'), 평균_총항해시간=('총항해시간', 'mean'), 평균_대기시간=('대기시간', 'mean'), 평균_항만정시성=('항만정시성', 'mean')).reset_index()
)

In [23]:
compare = pd.merge(
    daily_avg, total_df, on='기준일자', how='inner'
)

compare

,기준일자,평균_항만효율성,평균_총항해시간,평균_대기시간,평균_항만정시성,종합항만효율성,종합총항해시간,종합대기시간,종합항만정시성
0,2025-05-28,18.211111,341.750000,0.123333,3.035556,18.99,239.37,0.13,2.29
1,2025-06-11,20.122500,406.270000,0.025833,13.426667,21.48,280.38,0.06,10.84
2,2025-06-11,20.122500,406.270000,0.025833,13.426667,20.45,446.38,0.00,23.58
3,2025-06-30,21.222593,510.192222,0.112593,12.230741,20.06,324.43,0.19,5.72
4,2025-06-30,21.222593,510.192222,0.112593,12.230741,20.67,319.09,0.11,9.72
5,2025-06-30,21.222593,510.192222,0.112593,12.230741,19.70,299.25,0.07,13.01
6,2025-07-08,22.956000,562.422000,0.137000,-5.026000,21.16,361.97,0.12,4.02
7,2025-07-16,18.936667,269.520000,0.150000,-4.938333,19.06,251.70,0.11,0.90
8,2025-07-29,21.402500,427.820000,0.127500,6.186875,18.63,232.41,0.15,3.09
9,2025-07-29,21.402500,427.820000,0.127500,6.186875,19.45,326.72,0.07,7.87
10,2025-08-06,22.185556,617.950000,0.233333,3.797778,20.22,410.96,0.16,2.68
11,2025-08-13,20.572222,614.610000,0.143333,6.543333,18.81,338.23,0.14,9.48
12,2025-08-21,21.434444,512.616667,0.154444,0.501111,19.00,348.59,0.12,6.77
13,2025-08-28,18.391250,372.156250,0.125000,5.283750,17.66,248.71,0.16,5.94
14,2025-09-10,17.862353,467.552353,0.121765,5.000000,17.08,296.96,0.11,8.18
15,2025-09-10,17.862353,467.552353,0.121765,5.000000,17.85,283.97,0.15,12.52
16,2025-09-24,19.268889,543.921111,0.106667,10.617778,18.63,345.76,0.16,7.92
17,2025-10-15,18.191034,356.056207,0.144828,7.665862,20.14,417.01,0.16,11.44
18,2025-10-15,18.191034,356.056207,0.144828,7.665862,16.33,256.12,0.16,14.35
19,2025-10-15,18.191034,356.056207,0.144828,7.665862,15.64,344.93,0.11,6.84
20,2025-10-15,18.191034,356.056207,0.144828,7.665862,17.69,309.66,0.08,9.77
21,2025-10-22,19.580000,335.137143,0.375714,3.184286,18.96,297.64,0.24,10.14
22,2025-10-28,19.354000,325.354000,0.112000,8.890000,19.25,281.33,0.12,10.23
23,2025-11-05,19.584000,499.527000,0.089000,4.208000,18.51,391.86,0.04,7.61
24,2025-11-18,20.072667,436.472667,0.236667,-0.844667,17.05,269.17,0.31,6.18
25,2025-11-18,20.072667,436.472667,0.236667,-0.844667,18.23,348.45,0.11,8.00
26,2025-12-02,19.235714,538.391429,0.040000,16.204286,18.11,348.01,0.08,16.99
27,2025-12-08,18.968750,321.715000,0.128750,11.861250,17.26,271.29,0.08,16.01
28,2025-12-15,18.276667,572.303333,0.062222,15.551111,19.15,381.61,0.07,13.22
29,2025-12-22,21.468750,465.482500,0.048750,14.188750,19.77,375.56,0.04,14.26
30,2025-12-29,20.161429,434.414286,0.094286,10.190000,19.16,256.27,0.13,10.90
31,2026-01-05,23.504444,492.892222,0.426667,4.031111,21.63,340.49,0.25,3.80
32,2026-01-12,20.544444,416.388889,0.091111,12.654444,18.77,322.69,0.10,15.86
33,2026-01-19,16.090000,329.340000,0.100000,8.908000,18.15,317.36,0.08,10.85
34,2026-01-27,21.447143,442.571429,0.452857,8.765714,18.72,358.40,0.17,13.58
35,2026-02-02,19.037143,488.710000,0.141429,6.257143,19.52,319.92,0.13,13.01
36,2026-02-09,19.755000,534.927000,0.073000,-18.632000,19.22,404.11,0.05,-7.18
37,2026-02-23,19.742941,453.198824,0.077059,8.082941,19.51,389.80,0.07,7.38
38,2026-02-23,19.742941,453.198824,0.077059,8.082941,18.51,392.10,0.11,7.09
39,2026-03-09,19.980556,561.966111,0.123889,9.157778,18.64,308.87,0.07,8.54
40,2026-03-09,19.980556,561.966111,0.123889,9.157778,19.27,373.35,0.12,19.01
41,2026-03-16,16.630000,180.791667,0.061667,13.241667,16.92,190.01,0.07,17.65
42,2026-03-23,22.532500,406.843750,0.052500,12.093750,19.25,239.85,0.06,12.85
43,2026-03-30,21.570000,492.663333,0.123333,8.064444,19.60,343.87,0.09,12.19
44,2026-04-13,20.131765,492.029412,0.154706,7.290588,17.83,268.43,0.14,7.31
45,2026-04-13,20.131765,492.029412,0.154706,7.290588,17.23,351.85,0.08,12.06
46,2026-04-24,20.907143,453.794286,0.272857,0.251429,18.99,321.40,0.12,7.15
47,2026-04-27,18.265714,273.064286,0.072857,12.847143,18.23,291.21,0.07,10.38
48,2026-05-12,18.128333,297.868333,0.131667,-34.291667,18.25,266.87,0.14,-50.56
49,2026-05-29,18.731429,257.580000,0.062857,4.598571,19.13,283.98,0.05,6.37
50,2026-06-15,17.830909,342.720455,0.233636,4.761818,17.51,261.32,0.26,12.15
51,2026-06-15,17.830909,342.720455,0.233636,4.761818,18.34,228.35,0.25,8.69
52,2026-06-15,17.830909,342.720455,0.233636,4.761818,18.65,272.66,0.15,8.74
53,2026-06-22,22.706667,666.825556,0.065556,11.694444,18.81,435.13,0.06,13.19

In [24]:
route = df[df['도착항코드(DEST_PORT_CODE)'] != 'KPLI'].copy()

route.head()

,출발항코드(DEPARTURE_PORT_CODE),출발항명(DEPARTURE_PORT_NAME),도착항코드(DEST_PORT_CODE),도착항명(DEST_PORT_NAME),도착항국가(DEST_COUNTRY),기준일자(DATE),항만효율성(PORT_EFFICIENCY),총항해시간(TOTAL_SAILING_TIME),대기시간(WAITING_TIME),항만정시성(ON_TIME_PERFORMANCE)
0,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-05-28,23.69,644.50,0.0,7.94
1,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,22.01,608.54,0.0,16.20
2,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-11,16.52,749.45,0.0,1.36
3,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,22.37,634.28,0.0,7.44
4,KRPUS,부산항,AEJEA,제벨알리항,AE,2025-06-30,16.37,654.99,0.0,1.80

In [25]:
route_list = (route['도착항명(DEST_PORT_NAME)'].dropna().unique())
route_list

<ArrowStringArray>
[  '제벨알리항',  '안트베르펜항',    '상하이항',    '칭다오항',   '함부르크항',     '홍콩항',   '로테르담항',
   '싱가포르항',    '램차방항', '로스앤젤레스항',     '뉴욕항',    '호치민항']
Length: 12, dtype: str

In [32]:
result_list = []

for selected_route in route_list:

    filtered = route[route['도착항명(DEST_PORT_NAME)'] == selected_route].copy()

    sailing_time = filtered['총항해시간(TOTAL_SAILING_TIME)']

    mean = sailing_time.mean()
    q1 = sailing_time.quantile(0.25)
    q3 = sailing_time.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier = filtered[(sailing_time < lower_bound) | (sailing_time > upper_bound)]

    result_list.append({
        '노선': selected_route,
        '평균 총항해시간': mean,
        '전체 항해 건수': len(filtered),
        '이상치 건수': len(outlier),
        '이상치 비율': len(outlier) / len(filtered) * 100
    })

result = pd.DataFrame(result_list)

result

         노선     평균 총항해시간  전체 항해 건수  이상치 건수    이상치 비율
0     제벨알리항   647.047297        37       2  5.405405
1    안트베르펜항  1332.163913        23       1  4.347826
2      상하이항    40.304615        52       1  1.923077
3      칭다오항    39.991020        49       2  4.081633
4     함부르크항  1423.014000        15       0  0.000000
5       홍콩항    75.019355        31       0  0.000000
6     로테르담항  1335.029200        25       0  0.000000
7     싱가포르항   369.588889        54       3  5.555556
8      램차방항   267.626667         3       0  0.000000
9   로스앤젤레스항   351.327500        52       3  5.769231
10      뉴욕항   717.627429        35       2  5.714286
11     호치민항   209.709400        50       0  0.000000

In [29]:
fig = px.box(
    route,
    x='도착항명(DEST_PORT_NAME)',
    y='총항해시간(TOTAL_SAILING_TIME)',
    points='outliers',
    labels={
        '도착항명(DEST_PORT_NAME)': '도착항명',
        '총항해시간(TOTAL_SAILING_TIME)': '총항해시간'
    }
)

fig.show()